### ISSUE TITLE
RFC8295 Appendix A doesn't outline "how a full CSR can be included in the CSR Attributes response"

### ISSUE THREAD

**Issue by William-PanWei** [lamps-wg/lamps-rfc7030-csrattrs#2]
~~~~
Additionally, EST Extensions {{RFC8295}} Appendix A has an informative appendix that outlines how a full CSR can be included in the CSR Attributes response.
~~~~

I looked at RFC8295, but I didn't see Appendix A shows "how a full CSR can be included in the CSR Attributes response". Because the part related to CSR Attributes is as following:
~~~~
         --------------------->                     -+
   GET req:                                          | /csrattrs
         <---------------------                      |
                           GET res: attributes       |
~~~~

**Comment by seanturner** [comment]
This should probably say Appendices A & B; Appendix B is where the discussion is about to put a pKCS7PDU attribute in /csrattrs. Sorry should have checked the .mkd. @mcr you can probably close this issue as it was Closed via #11.
