### ISSUE TITLE
specify specific SN DN

### ISSUE THREAD

**Issue by mcr** [lamps-wg/lamps-rfc7030-csrattrs#6]
(TODO: Note that this mechanism does not support telling the client to include
in the CSR a specific subject DN, simply because there is no OID for this.
I think we should better make this clear,
or we have to define such an OID if setting a subject name should be supported.)

**Comment by DDvO** [comment]
A solution for this is meanwhile described in [section 3.3. ](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-rfc7030-csrattrs-07#section-3.3)[Alternative: Use of CSR templates](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-rfc7030-csrattrs-07#name-alternative-use-of-csr-temp).
We should make explicit in this section that it supports specifying a subject DN.

**Comment by mcr** [comment]
duplicates #9
