### ISSUE TITLE
Do we need to be able to specify the SubjectName?

### ISSUE THREAD

**Issue by mcr** [lamps-wg/lamps-rfc7030-csrattrs#9]
> As I (David) wrote on March 9th
    > <https://mailarchive.ietf.org/arch/msg/spasm/KSBlnRVVTcgpEAM8eA_uEssHY2I/>
    > and April 5th
    > <https://mailarchive.ietf.org/arch/msg/spasm/PqCEDBk_Vd59bDDxb7hVDg41PKM/>
    > and likely already before, while SANs can be expressed as part of an
    > extensionRequest CSR attribute, a regular subject field so far cannot
    > be expressed in a CsrAttrs structure.  This is because no OID has been
    > defined that could be used, e.g., in the 'type' field of a CSR
    > attribute and the CsrAttrs structure does not have any other field
    > where a subject Name could be placed.

**Comment by DDvO** [comment]
This is very related to #6. 
Note that a way to do this is meanwhile described in [section 3.3. ](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-rfc7030-csrattrs-07#section-3.3)[Alternative: Use of CSR templates](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-rfc7030-csrattrs-07#name-alternative-use-of-csr-temp).

**Comment by DDvO** [comment]
The new approach given in section 3.3 does allow specifying subject DNs.
